import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.coobird.thumbnailator.Thumbnails;
import net.proteanit.sql.DbUtils;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Prathmesh
 */
public class Main extends javax.swing.JFrame {
    
    private Connection conn;
    private PreparedStatement ps;
    private ResultSet rs;
    private byte[] byteImage;

    /**
     * Creates new form Main
     */
    public Main() {
        
        initComponents();
        disableAll();
        conn = MySQLConnect.getConnection();
        fillDataTable();
        
    }
    
    private void disableAll() {
        txtEnrollmentNo.setEnabled(false);
        txtName.setEnabled(false);
        txtAge.setEnabled(false);
        txtContact.setEnabled(false);
        taAddress.setEnabled(false);
        dcDob.setEnabled(false);
        rbtMale.setEnabled(false);
        rbtFemale.setEnabled(false);
        btnUploadImage.setEnabled(false);
        cmbQualification.setEnabled(false);
        
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        btnClear.setEnabled(false);
    }
    
    private void enableAll() {
        txtEnrollmentNo.setEnabled(true);
        txtName.setEnabled(true);
        txtAge.setEnabled(true);
        txtContact.setEnabled(true);
        taAddress.setEnabled(true);
        dcDob.setEnabled(true);
        rbtMale.setEnabled(true);
        rbtFemale.setEnabled(true);
        btnUploadImage.setEnabled(true);
        cmbQualification.setEnabled(true);
    }
    
    private void clearAll() {
        txtEnrollmentNo.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtContact.setText("");
        taAddress.setText("");
        txtImagePath.setText("");
        dcDob.setDate(null);
        cmbQualification.setSelectedIndex(0);
        rbtTemp.setSelected(false);
        lblImage.setIcon(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        rbtTemp = new javax.swing.JRadioButton();
        pnlBg = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEnrollmentNo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        rbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        txtAge = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        cmbQualification = new javax.swing.JComboBox<>();
        dcDob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        txtImagePath = new javax.swing.JTextField();
        lblImagePath = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblImage = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        scrollPaneDataTable = new javax.swing.JScrollPane();
        jtableData = new javax.swing.JTable();

        btnGroupGender.add(rbtTemp);
        rbtTemp.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(940, 875));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 350));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Enrollment No:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Gender:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Age:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Contact No:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Qualification:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("DOB:");

        txtEnrollmentNo.setNextFocusableComponent(txtName);

        txtName.setNextFocusableComponent(rbtMale);

        rbtMale.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGender.add(rbtMale);
        rbtMale.setText("Male");
        rbtMale.setNextFocusableComponent(txtAge);

        rbtFemale.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGender.add(rbtFemale);
        rbtFemale.setText("Female");
        rbtFemale.setNextFocusableComponent(txtAge);

        txtAge.setNextFocusableComponent(txtContact);

        txtContact.setNextFocusableComponent(cmbQualification);
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        cmbQualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select....", "MTech", "MS", "BTech.", "BCom.", "BA", "Diploma" }));
        cmbQualification.setName(""); // NOI18N
        cmbQualification.setNextFocusableComponent(dcDob);

        dcDob.setNextFocusableComponent(taAddress);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address:");

        btnUploadImage.setText("Upload Image");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        taAddress.setColumns(25);
        taAddress.setRows(5);
        taAddress.setNextFocusableComponent(btnUploadImage);
        jScrollPane2.setViewportView(taAddress);

        txtImagePath.setEditable(false);

        lblImagePath.setText("Image Path:");

        lblImage.setBackground(new java.awt.Color(204, 204, 204));
        lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        lblImage.setOpaque(true);

        jDesktopPane1.setLayer(lblImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(rbtMale)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                    .addComponent(rbtFemale))
                                .addComponent(txtName)
                                .addComponent(txtAge)
                                .addComponent(cmbQualification, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dcDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEnrollmentNo))
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblImagePath)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtEnrollmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(rbtMale)
                                    .addComponent(rbtFemale))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUploadImage))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(dcDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblImagePath)))))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(60, 60, 60)
                .addComponent(btnUpdate)
                .addGap(60, 60, 60)
                .addComponent(btnDelete)
                .addGap(60, 60, 60)
                .addComponent(btnClear)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        jPanel4.add(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableDataMouseClicked(evt);
            }
        });
        scrollPaneDataTable.setViewportView(jtableData);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneDataTable)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(scrollPaneDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.add(jPanel6);

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
         // TODO add your handling code here:
         
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        String message="Are you sure you want to delete thi record?";
        int ans=JOptionPane.showConfirmDialog(this, message,
                "Delete?",JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        
        if(ans == JOptionPane.YES_OPTION){
            String sql="DELTE FROM students WHERE enrollment_no= ?";
            
            try {
                ps=conn.prepareStatement(sql);
                ps.setInt(1,Integer.parseInt(txtEnrollmentNo.getText()));
                ps.execute();
                
                fillDataTable();
                
                btnUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
                
                clearAll();
                JOptionPane.showMessageDialog(this,
                        "Student deleted successfully",
                        "Deleted!",JOptionPane.INFORMATION_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,
                        "Some error while fetching student details",
                        "Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        if(btnUpdate.getText().equalsIgnoreCase("Update")){
            enableAll();
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(false);
            txtEnrollmentNo.setEnabled(false);
            btnUpdate.setText("Save Updates");
        }
        else {
            disableAll();
            updateData();
            fillDataTable();
            btnUpdate.setText("Update");
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void jtableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableDataMouseClicked
        // TODO add your handling code here:
        int selectedRow = jtableData.getSelectedRow();
            
            String enrollmentNumber =jtableData.getValueAt(selectedRow,0 ).toString();
            
            try {
                String sql="SELECT * FROM students WHERE enrollment_no= " + enrollmentNumber;
                ps=conn.prepareStatement(sql);
                rs=ps.executeQuery();
                if(rs.next()){
                    txtEnrollmentNo.setText(rs.getString("enrollment_no"));
                    txtName.setText(rs.getString("name"));
                    
                    String selectedGender=rs.getString("gender");
                    if("Male".equalsIgnoreCase(selectedGender)){
                        rbtMale.setSelected(true);
                    }else
                        rbtFemale.setSelected(true);
                    
                    txtContact.setText(rs.getString("contact_no"));
                    txtAge.setText(rs.getString("age"));
                    
                    cmbQualification.setSelectedItem(rs.getString("qualification"));
                    String dob=rs.getString("dob");
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    Date date=sdf.parse(dob);
                    dcDob.setDate(date);
                    
                    taAddress.setText(rs.getString("address"));
                    
                    byteImage=rs.getBytes("image");
                    BufferedImage image = ImageIO.read(new ByteArrayInputStream(byteImage));
                    ImageIcon icon=new ImageIcon(image);
                    lblImage.setIcon(icon);
                    
                    btnUpdate.setEnabled(true);
                    btnDelete.setEnabled(true);
                    
                }
            }
            catch(SQLException | ParseException | IOException e){
                JOptionPane.showMessageDialog(this
                        ,"Some error while fetching student details",
                        "Error!",JOptionPane.ERROR);
            }
    }//GEN-LAST:event_jtableDataMouseClicked

     private DefaultTableModel getStudentsTableModel(TableModel tm) {
        int nRow = tm.getRowCount();
        int nCol = tm.getColumnCount();
        
        Object[][] tableData = new Object[nRow][nCol];
        
        for(int i=0; i<nRow; i++) {
            for(int j=0; j<nCol-1; j++) {
                tableData[i][j] = tm.getValueAt(i, j);
            }
        }
        
        String colHeads[] = {"Enrollment No", "Name", "Gender", "Age", "Contact No", "DOB", "Qualification", 
            "Address"};
        
        DefaultTableModel tableModel = new DefaultTableModel(tableData, colHeads) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        return tableModel;
    }
    private void fillDataTable() {
        try {
            String sql = "SELECT "
                    + "enrollment_no, name, gender, age, contact_no, dob, qualification, address, image "
                    + "FROM students";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            jtableData.setModel(getStudentsTableModel(DbUtils.resultSetToTableModel(rs)));
            
        } catch(SQLException e) {
            String msg = e.getMessage();
            JOptionPane.showMessageDialog(this, msg,
                        "Error!",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
                // TODO add your handling code here:
        if(btnAdd.getText().equals("Add")){
            enableAll();
            clearAll();
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            btnAdd.setText("Save");
            btnClear.setEnabled(true);
            
        }
        else{
            insertData();
            disableAll();
            clearAll();
            fillDataTable();
            btnAdd.setText("Add");
        }
    }    
    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "gif");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(this);
        
        File sourceFile = chooser.getSelectedFile();
        if(sourceFile != null) {
            String sourceFilePath = sourceFile.getAbsolutePath();
            txtImagePath.setText(sourceFilePath);
            int lblImageHeight = lblImage.getHeight();
            int lblImageWidth = lblImage.getWidth();
            
            try {
                BufferedImage thumbnail;
                thumbnail = Thumbnails.of(sourceFile)
                                      .size(lblImageWidth, lblImageHeight)
                                      .asBufferedImage();
                
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(thumbnail,"jpg", baos);
                byteImage = baos.toByteArray();
                lblImage.setIcon(new ImageIcon(thumbnail));
            } catch(IOException e) {
                String msg = e.getMessage();
                JOptionPane.showMessageDialog(this, msg,
                        "Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }                                              

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        clearAll();
    }                                        

    private void insertData() {
        
        String enrollmentNo = txtEnrollmentNo.getText();
        String name = txtName.getText();
        String age = txtAge.getText();
        String contactNo = txtContact.getText();
        String address = taAddress.getText();
        String qualification = cmbQualification.getSelectedItem().toString();
        String gender = "";
        if(rbtMale.isSelected()) {
            gender = "Male";
        } else if(rbtFemale.isSelected()) {
            gender = "Female";
        }
        
        Date dob = dcDob.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dobString = sdf.format(dob);
        
        try {
            String sql = "INSERT INTO students("
                + "enrollment_no, name, contact_no, age, qualification, gender, "
                + "dob, address, image) VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            ps = conn.prepareStatement(sql);
            ps.setString(1, enrollmentNo);
            ps.setString(2, name);
            ps.setString(3, contactNo);
            ps.setString(4, age);
            ps.setString(5, qualification);
            ps.setString(6, gender);
            ps.setString(7, dobString);
            ps.setString(8, address);
            ps.setBytes(9, byteImage);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(this, "Record Inserted Successfully!", 
                    "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch(SQLException e) {
            String msg = e.getMessage();
            JOptionPane.showMessageDialog(this, msg,
                        "Error!",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void updateData(){
        String enrollmentNo=txtEnrollmentNo.getText();
        String name=txtName.getText();
        String age=txtAge.getText();
        String contactNo=txtContact.getText();
        String address=taAddress.getText();
         String qualification=cmbQualification.getSelectedItem().toString();
        String gender="";
        if(rbtMale.isSelected()){
            gender="Male";
        }
        else if(rbtFemale.isSelected()){
            gender="Female";
        }
        
        Date dob=dcDob.getDate();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String dobString =sdf.format(dob);
        
        try {
            String sql="UPDATE students SET "
                    +"name=? , contact_no=?,age=?,qualification=?,gender=?,"
                    + "dob=?,address=?,image=? WHERE enrollment_no=?";
            ps=conn.prepareStatement(sql);
            ps.setString(1,name);
            ps.setString(2,contactNo);
            ps.setString(3,age);
            ps.setString(4,qualification);
            ps.setString(5,gender);
            ps.setString(6,dobString);
            ps.setString(7,address);
            ps.setBytes(8,byteImage);
            ps.setString(9,enrollmentNo);
            ps.execute();
            
            JOptionPane.showMessageDialog(this,"Record updated successfully!",
                    "Success",JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException e){
            String msg=e.getMessage();
            JOptionPane.showMessageDialog(this, msg,"Error!",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
          



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JComboBox<String> cmbQualification;
    private com.toedter.calendar.JDateChooser dcDob;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtableData;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImagePath;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JRadioButton rbtMale;
    private javax.swing.JRadioButton rbtTemp;
    private javax.swing.JScrollPane scrollPaneDataTable;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEnrollmentNo;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
